name: External LLM Vulnerability Scan

on:
  workflow_call:
    inputs:
      base_ref:
        required: true
        type: string
      head_ref:
        required: true
        type: string
    secrets:
      CODE_ADVICE_URL:
        required: true

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch base branch and get diff
        id: diff
        run: |
          git fetch origin ${{ inputs.base_ref }}
          DIFF=$(git diff --unified=0 origin/${{ inputs.base_ref }} ${{ inputs.head_ref }})
          if [ -z "$DIFF" ]; then
            echo "No changes → skipping scan."
            echo "skip<<EOF" >> $GITHUB_OUTPUT
            echo "true"       >> $GITHUB_OUTPUT
            echo "EOF"        >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "patch<<EOF" >> $GITHUB_OUTPUT
          echo "$DIFF"     >> $GITHUB_OUTPUT
          echo "EOF"        >> $GITHUB_OUTPUT


      - name: Send diff to external vulnerability service
        if: steps.diff.outputs.skip != 'true'
        id: advice
        env:
          SERVICE_URL: ${{ secrets.CODE_ADVICE_URL }}
        run: |
          echo "${{ steps.diff.outputs.patch }}" > diff.patch

          RESPONSE=$(curl -sS \
            -X POST "${SERVICE_URL}" \
            -H "Accept: text/plain" \
            -H "Content-Type: text/plain" \
            --data-binary @diff.patch)

          echo "text<<EOF" >> $GITHUB_OUTPUT
          echo "$RESPONSE"  >> $GITHUB_OUTPUT
          echo "EOF"        >> $GITHUB_OUTPUT

      - name: Save scan output to file
        if: steps.diff.outputs.skip != 'true'
        run: |
          echo "${{ steps.advice.outputs.text }}" > scan.txt

      - name: Fail build on detected vulnerabilities
        if: steps.diff.outputs.skip != 'true'
        run: |
          if grep -q 'Issue' scan.txt; then
            echo "🚨 Vulnerabilities detected! Failing the build."
            cat scan.txt
            exit 1
          else
            echo "✅ No vulnerabilities found, build OK."
          fi